vim.g['todo#done'] = '✓'
vim.g['todo#undone'] = '✗'
vim.g['todo#quit'] = 'q'
vim.g['todo#quit2'] = '<Esc>'
vim.g['todo#check'] = '<CR>'
vim.g['todo#delete'] = 'd'
vim.g['todo#rename'] = 'r'
vim.g['todo#add'] = 'a'
